- name: Parchear SDK descargado por Buildozer
  run: |
    mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin
    touch $HOME/.buildozer/android/platform/android-sdk/tools/bin/android
    ln -sf /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager \
      $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
