# --- Android SDK/NDK Configuration ---
android.sdk_path = $ANDROIDSDK
android.ndk_path = $ANDROIDNDK
android.api = 31
android.minapi = 21

# --- Firma del APK ---
android.release_keystore = release.keystore
android.release_keyalias = palmargrande
android.release_keystore_pass = android
android.release_keyalias_pass = android

# --- Requisitos y configuración general ---
requirements = python3,kivy,pillow,kivy_garden.mapview,ffpyplayer,sdl2
source.dir = .
icon.filename = logo_app.jpeg
title = Palmar Grande
package.name = palmargrande
package.domain = org.angelithoom8
version = 1.0.0
