name: Build APK with Buildozer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-17-jdk autoconf automake libtool m4 unzip zip git
        pip install -U buildozer cython virtualenv kivy pillow kivy-garden ffpyplayer
        python3 -m pip install "kivy-garden.mapview==1.0.6"

    - name: Build APK
      run: |
        buildozer android debug
        mkdir -p output
        cp bin/*.apk output/

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: PalmarGrande-APK
        path: output/*.apk
