name: Build APK Release

on:
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias del sistema
      run: |
        sudo apt update
        sudo apt install -y build-essential libffi-dev libssl-dev libsqlite3-dev \
          libncurses5-dev libjpeg-dev libpng-dev libz-dev openjdk-17-jdk autoconf \
          automake libtool m4 unzip zip git wget

    - name: Instalar SDK y aceptar licencias
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
        sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;30.0.3"

    - name: Instalar Buildozer y librerías
      run: |
        pip install --upgrade pip
        pip install cython buildozer kivy pillow kivy-garden ffpyplayer
        pip install "kivy-garden.mapview==1.0.6"

    - name: Generar clave de firma temporal
      run: |
        keytool -genkey -v -keystore release.keystore -alias palmargrande \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -storepass android -keypass android \
          -dname "CN=Angel, OU=Dev, O=PalmarGrande, L=Corrientes, S=Corrientes, C=AR"

    - name: Configurar buildozer.spec
      run: |
        sed -i 's/^#\?title *=.*$/title = Palmar Grande/' buildozer.spec
        sed -i 's/^#\?package.name *=.*$/package.name = palmargrande/' buildozer.spec
        sed -i 's/^#\?package.domain *=.*$/package.domain = org.angelithoom8/' buildozer.spec
        sed -i 's/^#\?source.dir *=.*$/source.dir = ./' buildozer.spec
        sed -i 's|^#\?icon.filename *=.*$|icon.filename = logo_app.jpeg|' buildozer.spec
        sed -i 's/^#\?version *=.*$/version = 1.0.0/' buildozer.spec
        sed -i 's/^#\?requirements *=.*$/requirements = python3,kivy,pillow,kivy_garden.mapview,ffpyplayer,sdl2/' buildozer.spec
        echo "android.release_keystore = release.keystore" >> buildozer.spec
        echo "android.release_keyalias = palmargrande" >> buildozer.spec
        echo "android.release_keystore_pass = android" >> buildozer.spec
        echo "android.release_keyalias_pass = android" >> buildozer.spec
        echo "android.sdk_path = $HOME/android-sdk" >> buildozer.spec

    - name: Compilar APK en modo release
      run: |
        buildozer android clean || true
        buildozer -v android release || exit 1

    - name: Subir APK firmado
      uses: actions/upload-artifact@v4
      with:
        name: palmargrande-release-apk
        path: bin/*.apk
